import { CssBaseline } from "@mui/material";
import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import * as React from "react";
import { Navbar } from "./(app)/Navbar";
import { ClientLayout } from "./(app)/client-layout";
import "./globals.css";

const font = IBM_Plex_Sans({
  weight: ["500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "IHSMUN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientLayout>
          <Navbar />
          {children}
          <CssBaseline />
        </ClientLayout>
      </body>
    </html>
  );
}

